#   conda env create -f env.yml
name: ncbi_datasets
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda
  - python=3.7
  - gffread
  - pip
  - zip
  - ncbi-datasets-cli=15.34.0
  - unzip