name: Build gffread_python

on:
  workflow_dispatch

#When updating images change image tag below to correspond to changes
env:
  IMAGE_NAME: gffread_python
  IMAGE_TAG: python-3.10_Linux_x86_64

jobs:
  build:
    name: Build and push gffread_python image
    #Using ubuntu-22.04 instead of ubuntu-latest to use Docker 24 instead of Docker 25 as it causes gitpod issues
    runs-on: ubuntu-22.04

    steps:
    - name: Clean workspace before start
      run: rm -rf $GITHUB_WORKSPACE/*

    - uses: actions/checkout@v4.1.1

    - name: Check Docker version
      run: docker --version

    - name: Build Image
      id: build-image
      run: docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -f ${IMAGE_NAME}/Dockerfile . 

#      uses: redhat-actions/buildah-build@v2.12
#      with:
#        image: gffread_python
#        tags: python-3.10_linux_x86_64
#        containerfiles: gffread_python/Dockerfile
#
#    - name: Push To quay.io
#      id: push-to-quay
#      uses: redhat-actions/push-to-registry@v2.7
#      with:
#        image: ${{ steps.build-image.outputs.image }}
#        tags: ${{ steps.build-image.outputs.tags }}
#        registry: quay.io/ecoflowucl
#        username: ecoflowucl+dockerbuild
#        password: ${{ secrets.DOCKERBUILD_ROBOT_CREDENTIALS }}
#
#    - name: Print image url
#      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
#
#    - name: Clean workspace after finish
#      run: rm -rf $GITHUB_WORKSPACE/*
